server:
  port: 1001
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  application:
    name: test2-module
  cloud:
    nacos:
      password: Geit@86970000
      username: nacos
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: public
        enabled: false
logging:
  config: classpath:log4j2.xml
xcode:
  oss:
    access-key: minioadmin
    endpoint: 127.0.0.1:9000
    secret-key: minioadmin
    default-bucket: video
    init-buckets:
      - t851651
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: producer-group
#xcode:
#  xxl:
#    job:
#      access-token: default_token
#      appname: xxl-test
#      port: 9999
#      username: admin
#      password: 123456
#      enable: true
#      executorTitle: 测试执行器
#      admin-address: http://127.0.0.1:8080/xxl-job-admin
