spring:
  cloud:
    nacos:
      # Nacos 注册中心
      discovery:
        server-addr: ${common-variables.nacos-addr}
        enabled: true
        # Nacos 配置中心
        namespace: xk-learn
        group: DEFAULT_GROUP
      config:
        server-addr: ${common-variables.nacos-addr}
        file-extension: yaml
        namespace: xk-learn
        group: DEFAULT_GROUP
        refresh-enabled: true
  config:
    import:
      - optional:nacos:${common-variables.application-name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
