spring:
  application:
    name: xcode-dc-product
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: Geit@86970000
      discovery:
        enabled: true
        group: xcode
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: xcode
        import-check:
          enabled: true
  config:
    import:
      - optional:nacos:redis.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:common.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:knife4j.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:datasource.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:sa-token.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:rabbitmq.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:${spring.application.name}?group=xcode&refreshEnabled=true



