spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xcode-system?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      login-timeout: 10000
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1200000
      maximum-pool-size: 20
      minimum-idle: 1
      pool-name: HikariPool-1
      read-only: false

logging:
  config: classpath:log4j2.xml

server:
  port: 1240

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.xk.xcode.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  production: false
  setting:
    language: zh_cn
  basic:
    enable: true
    username: root
    password: 123456
