server:
  port: 4003
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: Geit@86970000
      discovery:
        enabled: true
        group: xcode
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: xcode
        import-check:
          enabled: true
  application:
    name: xcode-message
  config:
    import:
      - optional:nacos:redis.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:common.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:knife4j.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:datasource.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:sa-token.yaml?group=xcode&refreshEnabled=true
      - optional:nacos:rabbitmq.yaml?group=xcode&refreshEnabled=true
xcode:
  dict:
    enable: false
    cache-type: redis
  security:
    whitelist:
      - /api/message/sendMessage
  xxl:
    job:
      access-token: default_token
      appname: xxl-test
      port: 9999
      username: admin
      password: 123456
      enable: true
      executorTitle: 测试执行器
      admin-address: http://127.0.0.1:8080/xxl-job-admin
grpc:
  server:
    port: 3001